### ISSUE TITLE
"Accel+Shift+K" - I have never heard of an Accel-key!?

### ISSUE THREAD

**Issue by HeRo002** [tynn/duplicate-tab-hotkey#1]
This add-on sounds like what I need, but I can't use it, because I have never seen any "Accel" key on my keyboard...!?

**Comment by tynn** [comment]
On a Mac it's the `command` key. On all other systems it the `control` key.

**Comment by HeRo002** [comment]
OK! Why call it "Accel"??

**Comment by tynn** [comment]
That's a good question I cannot answer, sorry.
